[project]
name = "testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "hypothesis>=6.148.7",
    "pytest>=9.0.2",
    "requests>=2.32.5",
]
